/**
 * AI Operating Platform — PROJ-01: Tentaciones AI Commerce
 * 
 * FASE 162: Integración Real de Browser Runtime, Renderer 3D del Satélite y Validación Visual del Pipeline VTO.
 * Golden Journey End-to-End Verification Suite.
 * 
 * Invariants Formally Verified:
 * 1. Golden Journey 1: Full Cross-Layer Pipeline Integration (VideoFrame [F159] -> Continuous Loop [F160] ->
 *    Spatial Composite [F160] -> Render Descriptor [F161] -> Satellite Scene Spec [F162] ->
 *    Three.js Scene Bridge [F162] -> Rendered Output).
 * 2. Golden Journey 2: Out-of-Order Stale Rejection at Satellite Renderer Boundary (Seq 2 rendered ->
 *    Seq 1 arrives late -> rejected with STALE_FRAME_REJECTED -> Seq 3 accepted).
 * 3. Golden Journey 3: Interactive Viewport Fast-Path Manipulation (O(1) Pan, Zoom, Orbit
 *    directly updating 3D camera without restarting heavy CV inference).
 * 4. Golden Journey 4: Deterministic Resource Lifecycle & Zero-Leak Multi-Resource Disposal.
 * 
 * Evidence Level: E3 / E4 (IN-MEMORY / SIMULATED VERIFIED in Node.js test doubles;
 * WebGL / physical canvas runtime tagged as ENVIRONMENT PENDING).
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";

// Domain imports
import {
  DEFAULT_VIEWPORT_MODEL,
  RenderSceneDescriptor,
  RenderViewportModel,
} from "../../src/domain/vto/render-contract.js";
import {
  mapRenderDescriptorToSatelliteSpec,
  validateSatelliteVtoSceneSpec,
} from "../../src/domain/vto/satellite-render-contract.js";
import {
  SpatialWarpingCompositor,
  SpatialCompositionInput,
  SpatialWarpingComposite,
} from "../../src/domain/vto/spatial-warping-compositor.js";
import {
  createAffineWarpField,
} from "../../src/domain/vto/warp-field.js";

// Application imports
import {
  ContinuousProcessingCoordinator,
} from "../../src/application/vto/continuous-processing-coordinator.js";
import {
  SpatialToRenderMapper,
} from "../../src/application/vto/spatial-to-render-mapper.js";
import {
  InteractiveViewportController,
} from "../../src/application/vto/interactive-viewport-controller.js";
import {
  Satellite3DRendererAdapter,
} from "../../src/application/vto/satellite-3d-renderer-adapter.js";
import {
  TentacionesVtoSceneBridge,
} from "../../src/application/vto/tentaciones-vto-scene-bridge.js";
import {
  createSyntheticVideoFrame,
  SimulatedContinuousPipeline,
} from "../../src/application/vto/simulated-continuous-pipeline.js";
import {
  createSyntheticThreeEnvironment,
  createSyntheticCanvas,
  inspectBrowserRuntimeCapabilities,
} from "../../src/application/vto/satellite-vto-harness.js";

describe("Phase 162: Satellite Browser Runtime & 3D Renderer Integration Golden Journeys", () => {
  it("Golden Journey 1: Full Cross-Layer Pipeline Integration (VideoFrame -> Continuous Loop -> Spatial Composite -> Satellite 3D Scene)", async () => {
    // 1. Setup Synthetic Three.js Environment and Canvas (Satellite App layer doubles)
    const three = createSyntheticThreeEnvironment();
    const canvas = createSyntheticCanvas(1280, 720);

    // 2. Setup Continuous Pipeline Coordinator (Phase 160)
    const pipeline = new SimulatedContinuousPipeline();
    const coordinator = new ContinuousProcessingCoordinator({
      processingHandler: pipeline.createProcessingHandler(),
      maxQueueDepth: 3,
    });
    await coordinator.start();

    // 3. Setup Satellite 3D Renderer Adapter (Phase 162)
    const rendererAdapter = new Satellite3DRendererAdapter({
      sceneId: "tentaciones-gj-scene-1",
      canvas,
      threeInstance: three,
      satelliteAppName: "tentaciones-ai-commerce",
    });
    await rendererAdapter.initialize();
    assert.equal(rendererAdapter.getLifecycleState(), "READY");

    // 4. Connect Bridge (Phase 162)
    const bridge = new TentacionesVtoSceneBridge({
      coordinator,
      renderer: rendererAdapter,
      viewport: DEFAULT_VIEWPORT_MODEL,
      autoRender: true,
    });
    await bridge.initialize();
    assert.equal(bridge.isRunning(), true);

    // 5. Feed raw VideoFrame (Phase 159)
    const frame = createSyntheticVideoFrame({
      sequenceNumber: 1,
      width: 1280,
      height: 720,
    });
    const fed = await coordinator.feedFrame(frame);
    assert.equal(fed, true);

    // Allow asynchronous dispatch and bridge render loop cycle to complete
    await new Promise((r) => setTimeout(r, 40));

    // 6. Verify pipeline outputs across layers
    const composite = coordinator.getLatestValidResult();
    assert.ok(composite !== undefined, "Composite must be generated by Phase 160 coordinator");
    assert.equal(composite.sequenceNumber, 1);

    // 7. Verify Satellite 3D Renderer state
    assert.equal(rendererAdapter.getLatestRenderedSequence(), 1);
    assert.ok(rendererAdapter.getRenderedFrames().length >= 1);
    const lastResult = rendererAdapter.getLatestRenderResult();
    assert.ok(lastResult !== null);
    assert.equal(lastResult.rendered, true);
    assert.equal(lastResult.sequenceNumber, 1);
    assert.ok(lastResult.layersRenderedCount >= 1);

    // 8. Verify Three.js scene received meshes and rendered
    assert.ok(three.scene.children.length > 0, "Three.js scene must contain mesh objects");
    assert.ok(three.renderer.renderCalls > 0, "Three.js renderer must have executed render calls");
    assert.equal(three.renderer.domElement, canvas);

    // 9. Verify neutral specification mapping integrity
    const latestSpec = rendererAdapter.getLatestSatelliteSpec();
    assert.ok(latestSpec !== null);
    const validation = validateSatelliteVtoSceneSpec(latestSpec);
    assert.equal(validation.isValid, true);
    assert.equal(latestSpec.metadata.targetEngine, "threejs");

    // Cleanup
    await bridge.dispose();
    await coordinator.stop();
  });

  it("Golden Journey 2: Out-of-Order Stale Rejection at Satellite Renderer Boundary", async () => {
    const three = createSyntheticThreeEnvironment();
    const canvas = createSyntheticCanvas(1280, 720);

    const rendererAdapter = new Satellite3DRendererAdapter({
      sceneId: "tentaciones-gj-scene-stale",
      canvas,
      threeInstance: three,
      satelliteAppName: "tentaciones-ai-commerce",
    });
    await rendererAdapter.initialize();

    const makeDescriptor = (seq: number): RenderSceneDescriptor => {
      const warp = createAffineWarpField(4, 4, {
        translation: { x: seq * 0.01, y: 0 },
        scale: { x: 1, y: 1 },
        rotationDegrees: 0,
      });
      const input: SpatialCompositionInput = {
        frameId: `frame-${seq}`,
        sequenceNumber: seq,
        generation: 1,
        timestampMs: 1000 + seq * 33,
        dimensions: { width: 1280, height: 720 },
        warpField: warp,
      };
      const comp = SpatialWarpingCompositor.compose(input);
      return SpatialToRenderMapper.mapToSceneDescriptor(comp);
    };

    // Step A: Sequence 2 arrives and renders first
    const desc2 = makeDescriptor(2);
    const res2 = await rendererAdapter.renderScene(desc2);
    assert.equal(res2.rendered, true);
    assert.equal(res2.sequenceNumber, 2);
    assert.equal(rendererAdapter.getLatestRenderedSequence(), 2);

    // Step B: Sequence 1 arrives late (delayed worker inference) -> MUST BE REJECTED
    const desc1 = makeDescriptor(1);
    const res1 = await rendererAdapter.renderScene(desc1);
    assert.equal(res1.rendered, false);
    assert.equal(res1.reason, "STALE_FRAME_REJECTED");
    assert.equal(rendererAdapter.getLatestRenderedSequence(), 2, "Latest sequence must remain 2");

    // Step C: Sequence 3 arrives -> MUST BE ACCEPTED
    const desc3 = makeDescriptor(3);
    const res3 = await rendererAdapter.renderScene(desc3);
    assert.equal(res3.rendered, true);
    assert.equal(res3.sequenceNumber, 3);
    assert.equal(rendererAdapter.getLatestRenderedSequence(), 3);

    // Step D: Telemetry verification
    const dropped = rendererAdapter.getDroppedFrames();
    assert.equal(dropped.length, 1);
    assert.equal(dropped[0].sequenceNumber, 1);
    assert.equal(dropped[0].reason, "STALE_FRAME_REJECTED");

    const rendered = rendererAdapter.getRenderedFrames();
    assert.equal(rendered.length, 2);
    assert.equal(rendered[0].sequenceNumber, 2);
    assert.equal(rendered[1].sequenceNumber, 3);

    await rendererAdapter.dispose();
  });

  it("Golden Journey 3: Interactive Viewport Fast-Path Manipulation (O(1) Viewport Update Without CV Inference)", async () => {
    const three = createSyntheticThreeEnvironment();
    const canvas = createSyntheticCanvas(1280, 720);

    const coordinator = new ContinuousProcessingCoordinator();
    await coordinator.start();

    const rendererAdapter = new Satellite3DRendererAdapter({
      sceneId: "tentaciones-gj-scene-interactive",
      canvas,
      threeInstance: three,
      satelliteAppName: "tentaciones-ai-commerce",
    });
    await rendererAdapter.initialize();

    const bridge = new TentacionesVtoSceneBridge({
      coordinator,
      renderer: rendererAdapter,
      viewport: DEFAULT_VIEWPORT_MODEL,
    });
    await bridge.initialize();

    // Render an initial composite
    const warp = createAffineWarpField(4, 4, {
      translation: { x: 0, y: 0 },
      scale: { x: 1, y: 1 },
      rotationDegrees: 0,
    });
    const initialInput: SpatialCompositionInput = {
      frameId: "interactive-frame-1",
      sequenceNumber: 1,
      generation: 1,
      timestampMs: Date.now(),
      dimensions: { width: 1280, height: 720 },
      warpField: warp,
    };
    const initialComposite = SpatialWarpingCompositor.compose(initialInput);
    await bridge.updateSceneFromComposite(initialComposite);
    assert.equal(rendererAdapter.getLatestRenderedSequence(), 1);

    const initialRenderCalls = three.renderer.renderCalls;

    // Create interactive controller
    const controller = new InteractiveViewportController({
      initialViewport: DEFAULT_VIEWPORT_MODEL,
    });

    // User interaction: zoom, pan, orbit, mirror
    controller.zoomBy(1.25);
    controller.pan(25, -15);
    controller.orbit(10, 5);
    controller.setMirror(true);

    const updatedViewport = controller.getViewportModel();
    assert.equal(updatedViewport.zoom, 1.25);
    assert.equal(updatedViewport.translation.x, 25);
    assert.equal(updatedViewport.translation.y, -15);
    assert.equal(updatedViewport.isMirrored, true);

    // Fast-path render: Bridge updates viewport on the existing cached scene in O(1)
    const fastPathResult = await bridge.handleInteractiveViewportUpdate(updatedViewport);
    assert.equal(fastPathResult.rendered, true);
    assert.ok(three.renderer.renderCalls > initialRenderCalls, "Render calls must increment on interactive update");

    // Verify Three.js camera reflected the new viewport
    assert.equal(three.camera.aspect, updatedViewport.aspectRatio);

    // Verify touch unproject / project round-trip consistency
    const touchPoint = { x: 640, y: 360 };
    const worldPoint = controller.unproject(touchPoint);
    const screenPoint = controller.project(worldPoint);
    assert.ok(Math.abs(screenPoint.x - touchPoint.x) < 1e-4);
    assert.ok(Math.abs(screenPoint.y - touchPoint.y) < 1e-4);

    await bridge.dispose();
    await coordinator.stop();
  });

  it("Golden Journey 4: Deterministic Resource Lifecycle & Zero-Leak Multi-Resource Disposal", async () => {
    const three = createSyntheticThreeEnvironment();
    const canvas = createSyntheticCanvas(1280, 720);

    const rendererAdapter = new Satellite3DRendererAdapter({
      sceneId: "tentaciones-gj-scene-lifecycle",
      canvas,
      threeInstance: three,
      satelliteAppName: "tentaciones-ai-commerce",
    });
    await rendererAdapter.initialize();

    // Render sequence 1 with a textured mesh
    const warp = createAffineWarpField(4, 4, {
      translation: { x: 0, y: 0 },
      scale: { x: 1, y: 1 },
      rotationDegrees: 0,
    });
    const input: SpatialCompositionInput = {
      frameId: "lifecycle-frame-1",
      sequenceNumber: 1,
      generation: 1,
      timestampMs: Date.now(),
      dimensions: { width: 1280, height: 720 },
      warpField: warp,
    };
    const comp = SpatialWarpingCompositor.compose(input);
    const desc = SpatialToRenderMapper.mapToSceneDescriptor(comp);
    await rendererAdapter.renderScene(desc);

    // Verify active resources exist in the scene
    assert.ok(three.scene.children.length > 0);
    assert.equal(rendererAdapter.getLifecycleState(), "READY");

    // Perform disposal
    const receipt = await rendererAdapter.dispose();
    assert.ok(receipt);
    assert.equal(receipt.sceneId, "tentaciones-gj-scene-lifecycle");
    assert.equal(rendererAdapter.getLifecycleState(), "DISPOSED");
    assert.equal(three.scene.children.length, 0, "Scene children must be cleared");
    assert.equal(three.renderer.disposed, true, "Three.js renderer must be marked disposed");
    assert.equal(receipt.errors.length, 0, "Disposal must produce zero errors");

    // Fail-closed verification: Subsequent renderScene call throws or returns rejected
    const postDisposeDesc = SpatialToRenderMapper.mapToSceneDescriptor(comp);
    await assert.rejects(
      async () => {
        await rendererAdapter.renderScene(postDisposeDesc);
      },
      /DISPOSED/
    );

    // Fail-closed verification: Cannot initialize a disposed adapter
    await assert.rejects(
      async () => {
        await rendererAdapter.initialize();
      },
      /DISPOSED/
    );
  });

  it("Golden Journey 5: Capability Inspection & Environment Verification Honesty", () => {
    const report = inspectBrowserRuntimeCapabilities();

    // In Node.js headless runtime:
    assert.equal(typeof report.isBrowser, "boolean");
    assert.equal(typeof report.hasWebGL2, "boolean");
    assert.equal(typeof report.hasWebGPU, "boolean");
    assert.equal(typeof report.hasMediaDevices, "boolean");
    assert.equal(typeof report.statusSummary, "string");
    assert.ok(Array.isArray(report.recommendations));

    if (!report.isBrowser) {
      assert.equal(report.statusSummary, "ENVIRONMENT_PENDING: Headless Node.js runtime detected");
      assert.equal(report.hasWebGL2, false);
      assert.equal(report.hasWebGPU, false);
      assert.equal(report.hasMediaDevices, false);
    }
  });
});
